# Generated by Django 4.0.5 on 2022-06-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0002_brend'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('subID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsApp.category')),
            ],
        ),
    ]
