# Generated by Django 4.0.5 on 2022-06-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0003_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub',
            field=models.BooleanField(default=0),
        ),
    ]
